### PR TITLE
Hey! I have alredy add some important things in your project if you need something just tell

### PR DESCRIPTION
**Pull request by VladyslavMartynov**

### CODE REVIEW

**Comment by Spl4shh** [comment]
Actually I'm just training on some ideas and JS so i'll be looking on what you've done but not sure i'll merge it

**Comment by VladyslavMartynov** [comment]
> Actually I'm just training on some ideas and JS so i'll be looking on what you've done but not sure i'll merge 
I saw that you are just practicing , do not forget to add those feautures especially box-sizing : border-box!Good luck

**Comment by Spl4shh** [comment]
What is the property box-sizing ? I never used it

**Comment by Spl4shh** [comment]
and I know it's a lot that I ask but do you think that you can modifiy the CS without changing the HTML because I Think that the modification aren't obligatory

**Comment by VladyslavMartynov** [comment]
> What is the property box-sizing ? I never used it

You can google it sometimes people make mistakes without using it

**Review by Spl4shh — CHANGES_REQUESTED** [review]
don't want to modify the HTML 'cause I think that it isn't necessary

**Pull request closed without merging**
